/* RAILTYPE KOREA · 수도권 전철 7호선 데이터 · v21.0 공식 좌표·수면 GIS 재검증 */
(() => {
  "use strict";
  const station = (code, name, en, lat, lng) => ({ code, name, en, lat, lng });

  // 장암–온수는 서울교통공사 공개 좌표, 까치울–석남은 국가철도공단·인천교통공사 공개 역정보를 기준으로 구성합니다.
  // 2024년 역명 변경을 반영해 730역은 자양, 7호선 738역은 이수로 표시합니다.
  const stations = [
    station("711", "장암", "JANGAM", 37.700150, 127.053126),
    station("712", "도봉산", "DOBONGSAN", 37.689131, 127.046548),
    station("713", "수락산", "SURAKSAN", 37.677804, 127.055314),
    station("714", "마들", "MADEUL", 37.664985, 127.057701),
    station("715", "노원", "NOWON", 37.654478, 127.060555),
    station("716", "중계", "JUNGGYE", 37.645052, 127.064084),
    station("717", "하계", "HAGYE", 37.636363, 127.067999),
    station("718", "공릉", "GONGNEUNG", 37.625642, 127.072969),
    station("719", "태릉입구", "TAEREUNG", 37.617319, 127.074741),
    station("720", "먹골", "MEOKGOL", 37.610638, 127.077719),
    station("721", "중화", "JUNGHWA", 37.602604, 127.079254),
    station("722", "상봉", "SANGBONG", 37.595673, 127.085708),
    station("723", "면목", "MYEONMOK", 37.588671, 127.087503),
    station("724", "사가정", "SAGAJEONG", 37.580912, 127.088502),
    station("725", "용마산", "YONGMASAN", 37.573752, 127.086802),
    station("726", "중곡", "JUNGGOK", 37.565877, 127.084291),
    station("727", "군자", "GUNJA", 37.557151, 127.079484),
    station("728", "어린이대공원", "CHILDREN'S GRAND PARK", 37.547962, 127.074650),
    station("729", "건대입구", "KONKUK UNIV.", 37.540882, 127.071103),
    station("730", "자양", "JAYANG", 37.531558, 127.066714),
    station("731", "청담", "CHEONGDAM", 37.519097, 127.051851),
    station("732", "강남구청", "GANGNAM-GU OFFICE", 37.517185, 127.041220),
    station("733", "학동", "HAKDONG", 37.514262, 127.031738),
    station("734", "논현", "NONHYEON", 37.511108, 127.021385),
    station("735", "반포", "BANPO", 37.508171, 127.011717),
    station("736", "고속터미널", "EXPRESS BUS TERMINAL", 37.503387, 127.005055),
    station("737", "내방", "NAEBANG", 37.487640, 126.993541),
    station("738", "이수", "ISU", 37.485258, 126.981766),
    station("739", "남성", "NAMSEONG", 37.484688, 126.971108),
    station("740", "숭실대입구", "SOONGSIL UNIV.", 37.496258, 126.953649),
    station("741", "상도", "SANGDO", 37.502790, 126.947949),
    station("742", "장승배기", "JANGSEUNGBAEGI", 37.504845, 126.939025),
    station("743", "신대방삼거리", "SINDAEBANGSAMGEORI", 37.499717, 126.928218),
    station("744", "보라매", "BORAMAE", 37.499916, 126.920112),
    station("745", "신풍", "SINPUNG", 37.500107, 126.909806),
    station("746", "대림", "DAERIM", 37.492984, 126.896997),
    station("747", "남구로", "NAMGURO", 37.486181, 126.887372),
    station("748", "가산디지털단지", "GASAN DIGITAL COMPLEX", 37.480376, 126.882704),
    station("749", "철산", "CHEOLSAN", 37.476160, 126.868217),
    station("750", "광명사거리", "GWANGMYEONG SAGEORI", 37.479270, 126.854854),
    station("751", "천왕", "CHEONWANG", 37.486699, 126.838684),
    station("752", "온수", "ONSU", 37.492059, 126.823294),
    station("753", "까치울", "KKACHIOUL", 37.506236, 126.810950),
    station("754", "부천종합운동장", "BUCHEON STADIUM", 37.505380, 126.797350),
    station("755", "춘의", "CHUNUI", 37.503650, 126.787070),
    station("756", "신중동", "SINJUNGDONG", 37.503080, 126.776160),
    station("757", "부천시청", "BUCHEON CITY HALL", 37.504610, 126.763560),
    station("758", "상동", "SANG-DONG", 37.505770, 126.753080),
    station("759", "삼산체육관", "SAMSAN GYMNASIUM", 37.506430, 126.742080),
    station("760", "굴포천", "GULPOCHEON", 37.506950, 126.731480),
    station("761", "부평구청", "BUPYEONG-GU OFFICE", 37.508410, 126.720540),
    station("762", "산곡", "SANGOK", 37.508550, 126.703510),
    station("763", "석남", "SEONGNAM", 37.506210, 126.676210)
  ];

  const byName = new Map(stations.map((item) => [item.name, item]));
  const route = (names) => names.map((name) => ({ ...byName.get(name) }));

  window.LINE_7_ROUTES = {
    full: route([
      "장암",
      "도봉산",
      "수락산",
      "마들",
      "노원",
      "중계",
      "하계",
      "공릉",
      "태릉입구",
      "먹골",
      "중화",
      "상봉",
      "면목",
      "사가정",
      "용마산",
      "중곡",
      "군자",
      "어린이대공원",
      "건대입구",
      "자양",
      "청담",
      "강남구청",
      "학동",
      "논현",
      "반포",
      "고속터미널",
      "내방",
      "이수",
      "남성",
      "숭실대입구",
      "상도",
      "장승배기",
      "신대방삼거리",
      "보라매",
      "신풍",
      "대림",
      "남구로",
      "가산디지털단지",
      "철산",
      "광명사거리",
      "천왕",
      "온수",
      "까치울",
      "부천종합운동장",
      "춘의",
      "신중동",
      "부천시청",
      "상동",
      "삼산체육관",
      "굴포천",
      "부평구청",
      "산곡",
      "석남"
    ]),
    dobongsan: route([
      "도봉산",
      "수락산",
      "마들",
      "노원",
      "중계",
      "하계",
      "공릉",
      "태릉입구",
      "먹골",
      "중화",
      "상봉",
      "면목",
      "사가정",
      "용마산",
      "중곡",
      "군자",
      "어린이대공원",
      "건대입구",
      "자양",
      "청담",
      "강남구청",
      "학동",
      "논현",
      "반포",
      "고속터미널",
      "내방",
      "이수",
      "남성",
      "숭실대입구",
      "상도",
      "장승배기",
      "신대방삼거리",
      "보라매",
      "신풍",
      "대림",
      "남구로",
      "가산디지털단지",
      "철산",
      "광명사거리",
      "천왕",
      "온수",
      "까치울",
      "부천종합운동장",
      "춘의",
      "신중동",
      "부천시청",
      "상동",
      "삼산체육관",
      "굴포천",
      "부평구청",
      "산곡",
      "석남"
    ])
  };

  window.LINE_7_CONTEXTS = {
    "장암": { title: "수락산·중랑천 북단", subtitle: "의정부 장암동과 수락산 자락이 맞닿는 7호선 북쪽 종점", icon: "🏁", badge: "NORTHERN TERMINUS", area: "장암 생활권", keywords: "종점 · 산자락 · 중랑천" },
    "도봉산": { title: "도봉산 국립공원", subtitle: "1호선과 7호선이 만나는 서울 북부의 등산·환승 관문", icon: "⛰️", badge: "MOUNTAIN HUB", area: "도봉산 생활권", keywords: "등산 · 환승 · 북부 관문" },
    "수락산": { title: "수락산 등산로", subtitle: "암릉과 계곡으로 이어지는 수락산 동쪽 산행의 시작점", icon: "🥾", badge: "MOUNTAIN GATE", area: "상계 북부 생활권", keywords: "산행 · 계곡 · 주거" },
    "마들": { title: "마들근린공원", subtitle: "대단지 주거와 공원·체육시설이 이어지는 노원 북부 생활권", icon: "🌳", badge: "RESIDENTIAL PARK", area: "마들 생활권", keywords: "공원 · 주거 · 체육" },
    "노원": { title: "노원 문화의거리", subtitle: "4호선 환승과 대형 상권·학원가가 모인 동북권 중심지", icon: "🛍️", badge: "REGIONAL HUB", area: "노원 중심권", keywords: "환승 · 상권 · 교육" },
    "중계": { title: "중계동 학원가", subtitle: "은행사거리 교육 상권과 대단지 주거가 밀집한 노원 교육 중심", icon: "📚", badge: "EDUCATION DISTRICT", area: "중계 생활권", keywords: "학원가 · 주거 · 교육" },
    "하계": { title: "서울과학기술대학교 방면", subtitle: "중계천과 대학·주거단지가 이어지는 노원 남부 생활축", icon: "🎓", badge: "CAMPUS DISTRICT", area: "하계 생활권", keywords: "대학 · 주거 · 중계천" },
    "공릉": { title: "공릉동 국수거리", subtitle: "경춘선숲길과 대학가, 생활 상권이 연결되는 동북권 골목", icon: "🍜", badge: "LOCAL STREET", area: "공릉 생활권", keywords: "경춘선숲길 · 대학 · 골목" },
    "태릉입구": { title: "태릉·화랑대 생활권", subtitle: "6호선과 환승하며 노원·중랑·성북의 이동축이 만나는 지점", icon: "🚉", badge: "TRANSFER HUB", area: "태릉 생활권", keywords: "환승 · 태릉 · 주거" },
    "먹골": { title: "먹골역 생활상권", subtitle: "묵동 주거지와 중랑천 산책권이 가까운 조용한 역세권", icon: "🏘️", badge: "LOCAL DISTRICT", area: "묵동 생활권", keywords: "주거 · 중랑천 · 생활상권" },
    "중화": { title: "중화동 골목시장", subtitle: "중랑천과 전통 생활상권이 이어지는 중랑구 서부 주거지", icon: "🧺", badge: "NEIGHBORHOOD", area: "중화 생활권", keywords: "시장 · 주거 · 중랑천" },
    "상봉": { title: "상봉 광역교통거점", subtitle: "경의중앙선·경춘선과 연결되어 강원권까지 이어지는 철도 허브", icon: "🚆", badge: "RAIL HUB", area: "상봉 광역권", keywords: "광역철도 · 환승 · 상업" },
    "면목": { title: "면목동 생활권", subtitle: "전통시장과 주거 골목, 용마산 생활권이 이어지는 중랑의 중심", icon: "🏡", badge: "LOCAL DISTRICT", area: "면목 생활권", keywords: "시장 · 골목 · 주거" },
    "사가정": { title: "사가정공원", subtitle: "용마산 자락과 면목동 상권이 만나는 동부 생활 중심지", icon: "🌿", badge: "PARK DISTRICT", area: "사가정 생활권", keywords: "공원 · 상권 · 산자락" },
    "용마산": { title: "용마폭포공원", subtitle: "인공폭포와 암벽장, 용마산 등산로가 가까운 체육·녹지 구간", icon: "🧗", badge: "MOUNTAIN PARK", area: "용마산 생활권", keywords: "폭포 · 등산 · 체육" },
    "중곡": { title: "중곡동 가구거리", subtitle: "용마산 서쪽의 주거지와 생활 상권이 밀집한 광진 북부 지역", icon: "🏘️", badge: "LOCAL DISTRICT", area: "중곡 생활권", keywords: "가구거리 · 주거 · 상권" },
    "군자": { title: "군자 환승사거리", subtitle: "5호선과 7호선, 능동로 상권이 만나는 광진의 교통 중심", icon: "🚇", badge: "TRANSFER HUB", area: "군자 생활권", keywords: "환승 · 상권 · 능동로" },
    "어린이대공원": { title: "서울어린이대공원·세종대", subtitle: "공원과 캠퍼스, 공연시설이 모인 가족·대학 문화권", icon: "🎡", badge: "PARK & CAMPUS", area: "능동 생활권", keywords: "공원 · 대학 · 공연" },
    "건대입구": { title: "건대 맛의거리", subtitle: "2호선 환승과 캠퍼스·쇼핑·야간문화가 밀집한 동부 상권", icon: "🎓", badge: "CAMPUS HUB", area: "건대 생활권", keywords: "환승 · 캠퍼스 · 상권" },
    "자양": { title: "뚝섬한강공원", subtitle: "한강공원과 자벌레 문화공간으로 바로 이어지는 수변 관문", icon: "🌉", badge: "RIVERSIDE", area: "자양·한강 생활권", keywords: "한강공원 · 산책 · 수변문화" },
    "청담": { title: "청담대교·청담동", subtitle: "한강을 건넌 뒤 패션·갤러리 상권으로 이어지는 강남 북단", icon: "🖼️", badge: "RIVER & CULTURE", area: "청담 생활권", keywords: "한강 · 갤러리 · 패션" },
    "강남구청": { title: "강남구청·선정릉 방면", subtitle: "수인분당선 환승과 행정·업무 기능이 모인 강남 중심축", icon: "🏢", badge: "BUSINESS HUB", area: "청담·논현 생활권", keywords: "환승 · 행정 · 업무" },
    "학동": { title: "학동사거리", subtitle: "가구·인테리어 상권과 논현동 업무지가 이어지는 강남 생활축", icon: "🛋️", badge: "DESIGN DISTRICT", area: "논현 생활권", keywords: "인테리어 · 업무 · 상권" },
    "논현": { title: "논현동 먹자골목", subtitle: "신분당선 환승과 강남대로 상권이 만나는 야간문화 중심", icon: "🌃", badge: "URBAN HUB", area: "논현 생활권", keywords: "환승 · 음식 · 야간문화" },
    "반포": { title: "서래마을 방면", subtitle: "반포 주거단지와 서래마을·한강 생활권이 연결되는 서초 구간", icon: "🏙️", badge: "RESIDENTIAL HUB", area: "반포 생활권", keywords: "주거 · 서래마을 · 한강" },
    "고속터미널": { title: "서울고속버스터미널", subtitle: "3·7·9호선과 전국 버스망, 대형 상권이 결합된 광역교통 거점", icon: "🚌", badge: "NATIONAL HUB", area: "반포 광역권", keywords: "환승 · 고속버스 · 쇼핑" },
    "내방": { title: "서리풀공원", subtitle: "방배동 주거지와 서리풀공원 산책축이 만나는 서초 생활권", icon: "🌲", badge: "GREEN DISTRICT", area: "방배 생활권", keywords: "공원 · 주거 · 산책" },
    "이수": { title: "이수역 사거리", subtitle: "4호선과 7호선, 사당·방배 상권이 만나는 남부 환승 중심", icon: "🚉", badge: "TRANSFER HUB", area: "이수 생활권", keywords: "환승 · 상권 · 남부 교통" },
    "남성": { title: "남성시장·사당동", subtitle: "전통시장과 주거 골목이 이어지는 동작 서부 생활 중심", icon: "🧺", badge: "LOCAL MARKET", area: "사당 생활권", keywords: "시장 · 골목 · 주거" },
    "숭실대입구": { title: "숭실대학교", subtitle: "캠퍼스와 상도동 언덕 주거지가 이어지는 대학가", icon: "🎓", badge: "CAMPUS DISTRICT", area: "상도 생활권", keywords: "대학 · 언덕 · 청년문화" },
    "상도": { title: "상도동 생활권", subtitle: "장승배기로와 주거 골목, 학교가 밀집한 동작의 생활축", icon: "🏡", badge: "RESIDENTIAL AXIS", area: "상도 생활권", keywords: "주거 · 학교 · 골목" },
    "장승배기": { title: "동작구청 방면", subtitle: "동작구 행정시설과 노량진·상도 생활권을 잇는 교차점", icon: "🏛️", badge: "CIVIC DISTRICT", area: "장승배기 생활권", keywords: "행정 · 교차로 · 주거" },
    "신대방삼거리": { title: "성대골 생활권", subtitle: "보라매공원과 신대방·상도 주거지가 만나는 지역 상권", icon: "🌿", badge: "LOCAL HUB", area: "신대방 생활권", keywords: "공원 · 주거 · 상권" },
    "보라매": { title: "보라매공원", subtitle: "신림선 환승과 공원·의료·업무시설이 연결되는 서남권 거점", icon: "🌳", badge: "PARK & TRANSFER", area: "보라매 생활권", keywords: "환승 · 공원 · 업무" },
    "신풍": { title: "신풍시장", subtitle: "영등포 남부의 전통시장과 주거지가 이어지는 생활 중심", icon: "🛍️", badge: "LOCAL MARKET", area: "신길 생활권", keywords: "시장 · 주거 · 생활상권" },
    "대림": { title: "대림중앙시장", subtitle: "2호선 환승과 다문화 음식·시장 문화가 밀집한 서남권 거점", icon: "🥟", badge: "MULTICULTURAL HUB", area: "대림 생활권", keywords: "환승 · 시장 · 다문화" },
    "남구로": { title: "구로시장·G밸리 배후", subtitle: "생활시장과 산업단지 배후 주거지가 맞닿는 구로의 지역 중심", icon: "🏭", badge: "INDUSTRIAL DISTRICT", area: "남구로 생활권", keywords: "시장 · 산업 · 주거" },
    "가산디지털단지": { title: "G밸리", subtitle: "1호선과 7호선, 대규모 지식산업센터가 모인 디지털 업무지구", icon: "💻", badge: "TECH HUB", area: "가산 업무권", keywords: "환승 · IT · 업무" },
    "철산": { title: "철산상업지구", subtitle: "광명시청과 대형 상권·주거단지가 밀집한 광명의 중심지", icon: "🏙️", badge: "CITY CENTER", area: "철산 생활권", keywords: "행정 · 상업 · 주거" },
    "광명사거리": { title: "광명전통시장", subtitle: "전통시장과 구도심 상권, 목감천 생활권이 이어지는 교차점", icon: "🧺", badge: "MARKET HUB", area: "광명동 생활권", keywords: "시장 · 구도심 · 목감천" },
    "천왕": { title: "천왕산·천왕지구", subtitle: "서울 서남단의 신주거지와 녹지축이 만나는 관문", icon: "🌄", badge: "GREEN GATE", area: "천왕 생활권", keywords: "신도시 · 산책 · 서울 관문" },
    "온수": { title: "온수 환승거점", subtitle: "1호선과 7호선, 부천과 서울의 경계가 만나는 서남권 관문", icon: "🚇", badge: "BOUNDARY HUB", area: "온수 생활권", keywords: "환승 · 도시경계 · 주거" },
    "까치울": { title: "작동산·베르네천", subtitle: "부천 동부의 녹지와 주거지가 맞닿는 서울–부천 진입 구간", icon: "🌿", badge: "GREEN GATE", area: "까치울 생활권", keywords: "녹지 · 주거 · 도시경계" },
    "부천종합운동장": { title: "부천종합운동장", subtitle: "서해선 환승과 스포츠·문화시설이 모인 부천 북부 거점", icon: "🏟️", badge: "SPORTS HUB", area: "춘의 생활권", keywords: "환승 · 경기장 · 문화" },
    "춘의": { title: "부천로 산업·생활축", subtitle: "종합운동장과 부천 도심 사이의 산업·주거 기능이 이어지는 구간", icon: "🏭", badge: "URBAN INDUSTRY", area: "춘의 생활권", keywords: "산업 · 주거 · 도심" },
    "신중동": { title: "중동 신도시 상권", subtitle: "백화점·업무시설과 대단지 주거가 밀집한 부천 신도시 중심", icon: "✨", badge: "NEW TOWN HUB", area: "중동 생활권", keywords: "상업 · 업무 · 신도시" },
    "부천시청": { title: "부천시청·중앙공원", subtitle: "행정시설과 중앙공원, 문화상권이 모인 부천의 대표 중심지", icon: "🏛️", badge: "CIVIC CENTER", area: "중동 행정권", keywords: "행정 · 공원 · 문화" },
    "상동": { title: "상동호수공원 방면", subtitle: "대형 상업시설과 신도시 주거, 공원 생활권이 이어지는 부천 서부", icon: "🌊", badge: "NEW TOWN", area: "상동 생활권", keywords: "호수공원 · 쇼핑 · 주거" },
    "삼산체육관": { title: "삼산월드체육관", subtitle: "대형 체육관과 굴포천, 부천·인천 생활권이 만나는 경계역", icon: "🏀", badge: "SPORTS DISTRICT", area: "삼산 생활권", keywords: "체육 · 굴포천 · 도시경계" },
    "굴포천": { title: "굴포천 생태하천", subtitle: "수변 산책로와 삼산·갈산 주거지가 이어지는 부평 북부 구간", icon: "💧", badge: "RIVERSIDE", area: "굴포천 생활권", keywords: "생태하천 · 산책 · 주거" },
    "부평구청": { title: "부평구청", subtitle: "인천 1호선 환승과 행정·업무 기능이 결합된 부평의 교통 중심", icon: "🏢", badge: "TRANSFER HUB", area: "부평 행정권", keywords: "환승 · 행정 · 업무" },
    "산곡": { title: "산곡동 주거지", subtitle: "원적산 자락과 대단지 주거가 이어지는 인천 북부 생활권", icon: "⛰️", badge: "RESIDENTIAL DISTRICT", area: "산곡 생활권", keywords: "원적산 · 주거 · 생활상권" },
    "석남": { title: "석남 거북시장", subtitle: "인천 2호선과 환승하며 서해구 생활권으로 이어지는 7호선 서쪽 종점", icon: "🏁", badge: "WESTERN TERMINUS", area: "석남 생활권", keywords: "종점 · 환승 · 전통시장" }
  };
})();
